spring:
  cloud:
    gateway:
      routes:
      - id: servlet-app
        uri: http://localhost:8000
        predicates:
        - Path=/profile,/
        filters:
        - TokenRelay=
okta:
  oauth2:
    client-secret: $clientSecret
    client-id: $clientId
    issuer: https://$oktaDomain/oauth2/default
